name: openfeature_provider_intellitoggle_client
description: Public-safe IntelliToggle snapshot provider for the OpenFeature Dart Client SDK.
version: 0.0.1-alpha.2
publish_to: none
homepage: https://intellitoggle.com
repository: https://gitlab.com/dartapps/apps/intellitoggle/openfeature-provider-intellitoggle

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  openfeature_dart_client_sdk:
    git:
      url: https://github.com/open-feature/dart-server-sdk.git
      ref: a441a79a34cb60dfad64feb5230fabe0dc1bff72
      path: packages/openfeature_dart_client_sdk

dev_dependencies:
  lints: ^6.0.0
  test: ^1.31.2
