name: intellitoggle_openfeature
description: IntelliToggle provider for OpenFeature Dart Server SDK
version: 0.1.0
homepage: https://intellitoggle.com
repository: https://github.com/intellitoggle/openfeature-dart

environment:
  sdk: ^3.7.2

dependencies:
  openfeature_dart_server_sdk: ^0.0.9
  http: ^1.1.0
  meta: ^1.9.1

dev_dependencies:


